from hades_bot.core.scope import is_hades_scope_allowed, scope_block_reason


def test_hard_off_topic_stays_blocked():
    assert not is_hades_scope_allowed("Can you explain Python decorators?")
    assert scope_block_reason("Can you explain Python decorators?")


def test_short_followup_requires_history():
    assert not is_hades_scope_allowed("why?", has_history=False)
    assert not is_hades_scope_allowed("huh?", has_history=False)
    assert is_hades_scope_allowed("same", has_history=False)
    assert is_hades_scope_allowed("fair enough", has_history=False)
    assert is_hades_scope_allowed("go ahead", has_history=False)
    assert is_hades_scope_allowed("woof woof!", has_history=False)
    assert is_hades_scope_allowed("meow :3", has_history=False)
    assert is_hades_scope_allowed("Ayooo!", has_history=False)
    assert is_hades_scope_allowed("Ayooo:DuduLevi:", has_history=False)
    assert is_hades_scope_allowed("Woahhh :Pepeuwu:", has_history=False)
    assert is_hades_scope_allowed("💀", has_history=False)
    assert is_hades_scope_allowed("😭😭", has_history=False)
    assert is_hades_scope_allowed("owo", has_history=False)
    assert is_hades_scope_allowed("Eh like what???", has_history=False)
    assert is_hades_scope_allowed("like what?", has_history=False)
    assert is_hades_scope_allowed("what else?", has_history=False)
    assert is_hades_scope_allowed("Ok as u say so I'll get out of the shadows", has_history=False)
    assert is_hades_scope_allowed("you too", has_history=False)
    assert is_hades_scope_allowed("no way", has_history=False)
    assert is_hades_scope_allowed("why?", has_history=True)
    assert is_hades_scope_allowed("What do u mean?", has_history=False)
    assert is_hades_scope_allowed("wdym?", has_history=False)
    assert not is_hades_scope_allowed("what's this?", has_history=False)
    assert is_hades_scope_allowed("what's this?", has_history=True)
    assert is_hades_scope_allowed("what does that mean?", has_history=True)
    assert is_hades_scope_allowed("No, I meant the other one.", has_history=False)
    assert is_hades_scope_allowed("Not exactly, I meant the other one.", has_history=False)
    assert is_hades_scope_allowed("That's not what I meant.", has_history=False)
    assert is_hades_scope_allowed("I meant the other one.", has_history=False)
    assert is_hades_scope_allowed("nahhh", has_history=False)
    assert is_hades_scope_allowed("ikr", has_history=False)
    assert is_hades_scope_allowed("Hades, what do you think of puppets?")
    assert is_hades_scope_allowed("Hades, tell me about Oneiroi.")
    assert is_hades_scope_allowed("Hades, tell me about Odin.")
    assert is_hades_scope_allowed("Can I take you out to dinner?")
    assert is_hades_scope_allowed("Want to go on a date?")
    assert is_hades_scope_allowed("May I take a whiff of your scent?")
    assert is_hades_scope_allowed("Can I sniff behind your ears?")
    assert is_hades_scope_allowed("How did you know?", has_history=True)
    assert is_hades_scope_allowed("What can I do for you?", has_history=False)
    assert is_hades_scope_allowed("what can I do for u?", has_history=False)
    assert is_hades_scope_allowed("anyways what can I do for u?", has_history=False)
    assert is_hades_scope_allowed("Well, anything I can do for you?", has_history=False)
    assert is_hades_scope_allowed("What else to do with u?", has_history=False)
    assert is_hades_scope_allowed("What else can we do together?", has_history=False)
    assert is_hades_scope_allowed("how abt to drink some tea???", has_history=False)
    assert is_hades_scope_allowed("How about tea?", has_history=False)
    assert is_hades_scope_allowed("Want some tea?", has_history=False)
    assert is_hades_scope_allowed("Let's have some tea.", has_history=False)
    assert is_hades_scope_allowed("Ok, what do u like then?", has_history=False)
    assert is_hades_scope_allowed("Let's hang out sometime.", has_history=False)
    assert is_hades_scope_allowed("Can we spend some time together?", has_history=False)
    assert is_hades_scope_allowed("Hades, tell me about painting.", has_history=False)
    assert is_hades_scope_allowed("Hades, what do you think about stagecraft?", has_history=False)
    assert is_hades_scope_allowed("What should I do tonight?", has_history=False)
    assert is_hades_scope_allowed("What else to do with u?", has_history=False)
    assert is_hades_scope_allowed("What else can we do together?", has_history=False)


def test_hades_social_and_admiration_scope():
    assert is_hades_scope_allowed("Tell me about Mintha.")
    assert is_hades_scope_allowed("Hey Hades, how are you?")
    assert is_hades_scope_allowed("You're very elegant.")
    assert is_hades_scope_allowed("Eh ur so hot")
    assert is_hades_scope_allowed("ur so hot")
    assert is_hades_scope_allowed("u look pretty")
    assert is_hades_scope_allowed("Eh I mean ur the one who drew my attention to u :v")
    assert is_hades_scope_allowed("you keep catching my eye")
    assert is_hades_scope_allowed("you're hilarious")
    assert is_hades_scope_allowed("huh?", has_history=True)
    assert is_hades_scope_allowed("wait what", has_history=True)
    assert is_hades_scope_allowed("go ahead", has_history=True)
    assert is_hades_scope_allowed("I wanted to see you")
    assert is_hades_scope_allowed("I've been thinking about you")
    assert not is_hades_scope_allowed("huh?", has_history=False)
    assert not is_hades_scope_allowed("Tell me the capital of France.")

def test_scope_block_reason_matches_refusal_catalog():
    assert scope_block_reason("Explain Python decorators.") == "programming or specialist work" or scope_block_reason("Explain Python decorators.") == "programming or software development"
    assert scope_block_reason("What sport is on tonight?") == "sports"
